# constant variables

BORDER_THICKNESS = 5
POSITION_NUMBER = 8
LANE_NUMBER = 3
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
MARGIN = 20
LANE_HEIGHT_CONST = 200
CARD_COUNT = 5
AMNESIA_BAR_COUNT = 4
AMNESIA_BAR_STARTING_X = 0
AMNESIA_BAR_STARTING_Y = 0
