# constant variables

BORDER_THICKNESS = 5
COL_NUMBER = 8
ROW_NUMBER = 3
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
MARGIN = 20
LANE_STARTING_X = 480
LANE_STARTING_Y = WINDOW_HEIGHT
LANE_HEIGHT_CONST = WINDOW_HEIGHT
COL_START = LANE_STARTING_X
CARD_COUNT = 5
AMNESIA_BAR_COUNT = 4
AMNESIA_BAR_STARTING_X = 0
AMNESIA_BAR_STARTING_Y = 0
