# constant variables

BORDER_THICKNESS = 5
COL_NUMBER = 8
ROW_NUMBER = 3
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
MARGIN = 20
LANE_START_X = 480 + MARGIN
LANE_START_Y = WINDOW_HEIGHT / 6
LANE_HEIGHT = WINDOW_HEIGHT / 6
COL_START = LANE_START_X
COL_WIDTH = (WINDOW_WIDTH - LANE_START_X - MARGIN) / COL_NUMBER + 4
CARD_COUNT = 5
